# -*- coding: utf-8 -*-
"""Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pa44kOHZfL83PTJciPA7_ZVzHZog1EO

# **Project Overview**

# **Anime Recommendation System**

Building an Anime Recommendation System using Cosine Similarity based on features like:

->Genre

->Rating

->Episodes

->Popularity (members)

This is a content-based filtering system (not collaborative filtering).
"""

# Step 1: Import Libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Step 2: Load Dataset
df = pd.read_csv("/content/anime.csv")
df.head()

df

df.info()

df.isnull().sum()

print(df.describe())
print(df['genre'].head())

print(df[['rating', 'episodes', 'members']].isnull().sum())

# Step 3: Data Preprocessing
# Handle missing values
df['genre'] = df['genre'].fillna('')
df['rating'] = df['rating'].fillna(df['rating'].mean())

df['episodes'] = df['episodes'].replace('Unknown', np.nan)
# Convert types before calculating median or filling NaN
df['episodes'] = df['episodes'].astype(float)
df['episodes'] = df['episodes'].fillna(df['episodes'].median())

df['members'] = df['members'].fillna(df['members'].median())


# Step 4: Feature Extraction
# Vectorize genre
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=lambda x: x.split(','), token_pattern=None)
genre_matrix = cv.fit_transform(df['genre'])

# Normalize numerical features
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
num_features = scaler.fit_transform(df[['rating', 'episodes', 'members']])

# Combine
from scipy.sparse import hstack
feature_matrix = hstack([genre_matrix, num_features])

# Step:5 Compute Cosine Similarity

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(feature_matrix)

# Step 6: Recommendation Function
def recommend_anime(title, n=10):
    idx = df[df['name'] == title].index[0]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:n+1]

    anime_indices = [i[0] for i in sim_scores]

    return df['name'].iloc[anime_indices].values

print(recommend_anime("Naruto"))

# Step 7: Threshold-Based Recommendations
def recommend_with_threshold(title, threshold=0.5):
    idx = df[df['name'] == title].index[0]

    sim_scores = list(enumerate(cosine_sim[idx]))

    filtered = [i for i in sim_scores if i[1] > threshold]

    filtered = sorted(filtered, key=lambda x: x[1], reverse=True)

    anime_indices = [i[0] for i in filtered[1:]]

    return df['name'].iloc[anime_indices]

for anime in recommend_with_threshold("Naruto", 0.6):
    print(anime)

import pickle
pickle.dump(cosine_sim, open('cosine_sim.pkl', 'wb'))

